version: '3'

services:
  frontend:
    build: ./client
    container_name: usr-client
    ports:
      - "82:82"
    depends_on:
      - backend
    networks:
      - authentication-network

  backend:
    build: ./api
    container_name: usr-back
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - authentication-network

  mongo:
    image: mongo:4.4.6
    container_name: mongo-manag
    ports:
      - "27024:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - authentication-network

volumes:
  mongo-data:
    

networks:
   authentication-network:
    driver: bridge

