version: '3'

services:
  backend:
    build:
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/authentication
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "82:82"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 
