version: '3'

services:
  frontend:
    build: ./client
    container_name: usr-client
    ports:
      - "82:82"
    depends_on:
      - backend
    networks:
      - management-network

  backend:
    build: ./api
    container_name: usr-back
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - management-network

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-management:/data/db
    networks:
      - management-network

volumes:
  mongo-data-management:
    

networks:
   management-network:
    driver: bridge
